" NeoBundle Scripts
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/boinc/.vim/bundle/neobundle.vim/

" Required:
call neobundle#begin(expand('/home/boinc/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:
NeoBundle 'itchyny/lightline.vim'

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
" End NeoBundle Scripts

" Basic config 

" LightLine
set laststatus=2
set noshowmode
let g:lightline = {'colorscheme': 'wombat', }
