" Turn on pathogen
execute pathogen#infect()

" Cancels compatibilirt with Vi
set nocompatible

" Change tke esc key by ;;
imap ;; <Esc>
map ;; <Esc>

" Turn on the plugin mode
filetype indent plugin on

" Enable syntax highlighting
syntax on
colorscheme flattown
highlight LineNr ctermfg=grey ctermbg=none

" Better command-line completion
set wildmenu

" Update title
set title

" Show commands in the last line
set showcmd

" Highlight searches
set hlsearch

" Ignore case sensitive search, except with capital letters
set ignorecase
set smartcase

" Allow backspacing over autoindent
set backspace=indent,eol,start

" Keep the same indent
set autoindent

" Display line numbers
set number

" Indentation options
set shiftwidth=4
set softtabstop=4
set expandtab

